// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-vibes/Hearth.tsx": () => import("../components/mockups/login-vibes/Hearth.tsx"),
  "./components/mockups/login-vibes/Quiet.tsx": () => import("../components/mockups/login-vibes/Quiet.tsx"),
  "./components/mockups/login-vibes/Rack.tsx": () => import("../components/mockups/login-vibes/Rack.tsx")
};
